---
name: publish

on:
    workflow_dispatch:
    push:
        branches: [main]

permissions: write-all

jobs:
    publish-docker-image:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v2
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build the hello-world Docker image
              run: |-
                  docker build . --tag ghcr.io/kilianp07/prestashop-backup-to-cloud:latest
                  docker push ghcr.io/kilianp07/prestashop-backup-to-cloud:latest
